### ISSUE TITLE
 installation pre-check failed

### ISSUE THREAD

**Issue by dinism** [mudrd8mz/moodle-mod_poster#6]
There is a request to install plugin Poster (mod_poster) version 2015102601 from the Moodle plugins directory on this site. However, the plugin installation pre-check failed (reason code: remoteunavailable)
Moodle 3.1.3+ (Build: 20161115)

**Comment by mudrd8mz** [comment]
Yeah, there is a short delay between when the plugin is uploaded to the plugins directory and when it becomes available for on-click installation from within the moodle admin interface. Please give it a while (should be no longer than an hour IIRC) so that all the systems can get synced and try to repeat then. Thanks in advance.
