### ISSUE TITLE
Populating the poster content into topics

### ISSUE THREAD

**Issue by wullie** [mudrd8mz/moodle-mod_poster#7]
I think it would be good to have the option to be able to display the poster contents onto the main course page (similar to a label or a folder inline display). 

Used in conjunction with the OneTopic format, this would be a good way to display information in Moodle, similar to a collection of pages in Mahara.

**Comment by mudrd8mz** [comment]
As commented in the plugins directory, you can currently use "Single activity format" and let the poster be displayed directly as the course main page.

**Comment by wullie** [comment]
Thanks for the feedback David and that's something I never thought of. That
would only really give me one page as opposed to a collection of pages
though.

**Comment by mudrd8mz** [comment]
@dasistwas implemented this feature in pull #9 

During the review and testing, it turned out the actual behaviour is not as intuitive as we originally assumed. Particularly, some blocks display their contents depending on the context of the page the block is shown. When blocks are shown at the module's view page, the context of the page is the context of the activity. But when they are shown in the context of the course main page (as is requested here), the page context is the course context.

This leads to counter-intuitive behaviour with blocks like Comments and others. There seems to be no easy way to work around this (intentional) behaviour and so I decided to reject this feature request. I believe it is better if the module does one thing with a consistent and predictable behaviour.

Thank you for understanding.
