### ISSUE TITLE
Not all blocks are available?

### ISSUE THREAD

**Issue by ewout** [mudrd8mz/moodle-mod_poster#8]
I wonder which blocks should be available for adding to a poster page. In my site the calendar block, for example, is not available, as shown in the screenshot below. What could the cause be?
![selecao_019](https://user-images.githubusercontent.com/6329/34649482-654876ee-f397-11e7-8528-37b7f9a8566d.png)

**Comment by mudrd8mz** [comment]
Yeah, the problem is that not all blocks declare themselves as being addable on an activity page (and Poster is an activity). The way around is to:
1. Add the block on the course page
2. Let it display on all course pages
3. Go to Poster, edit the block setting there.
4. Change it to appear on this Poster page only.

It is quite non-intuitive but that is how blocks work in Moodle.

**Comment by ewout** [comment]
Thanks! I hadn't noticed item 6 in https://moodle.org/plugins/mod_poster
